### ISSUE TITLE
Ternary Operator Expression Error

### ISSUE THREAD

**Issue by v4ssili** [shepherdwind/simple-evaluate#11]
Me again :)

I found an issue regarding the evaluation of ternary operator expressions:

`5 == 5 ? 4 : 1` results in 4, good
`1 == 1 ? 1 : 0` results in 1, good
`0 == 0 ? 0 : 1` results in 1, unexpected; apparently 0 is not equal to 0

just `0 == 0` results in true though, so it must be something with the ternary operator

**Comment by shepherdwind** [comment]
new version 1.4.6 published

**Comment by pavelicious-dev** [comment]
much appreciated!
