### ISSUE TITLE
Parentheses and ternary operators / complex formulae

### ISSUE THREAD

**Issue by pavelicious-dev** [shepherdwind/simple-evaluate#12]
We stumbled upon another small issue for our evaluations with more complex formulae, hope you can look into it again:

`'v1_3==v1_1?1:0+v2_2==v2_1?1:0+v3_1==v3_1?1:0+v4_3==v4_1?1:0'`
expected: 1, received: 1 ✅ 

the same with parentheses
`'(v1_3==v1_1?1:0)+(v2_2==v2_1?1:0)+(v3_1==v3_1?1:0)+(v4_3==v4_1?1:0)'`
expected: 1, received: 4 ⛔ 

all conditions match, no parentheses
`'v1_3==v1_3?1:0+v2_2==v2_2?1:0+v3_1==v3_1?1:0+v4_3==v4_3?1:0'`
expected: 4, received: 1 ⛔ 

parentheses but all blocks are true
`'(g1_1==g1_1?1:0)+(g2_1==g2_1?1:0)+(g3_1==g3_1?1:0)+(g4_1==g4_1?1:0)+(g5_1==g5_1?1:0)'`
expected: 5, received: 5 ✅ 

not all match
`'(g1_1==g1_2?1:0)+(g2_1==g2_1?1:0)+(g3_1==g3_4?1:0)+(g4_1==g4_1?1:0)+(g5_1==g5_1?1:0)'`
expected: 3, received: 5 ⛔ 

Thanks in advance!

**Comment by shepherdwind** [comment]
There are so many variables here, can you provide the values of the variables? For example v1_3 , v1_3 , what are they values?

**Comment by pavelicious-dev** [comment]
In this concrete scenario they were just strings values `"v1_3"=="v1_3"`.
but we also use it a lot with integers

is it that I'm just missing the quotes in the formula so they're regarded as variables that cannot be evaluated?
if so, what is the default behavior? would an `(undefined==undefined?1:0)` not be truthy?

**Comment by shepherdwind** [comment]
Based on the example you provided, I replaced all the variables with undefined

`(v1_3==v1_1?1:0)+(v2_2==v2_1?1:0)+(v3_1==v3_1?1:0)+(v4_3==v4_1?1:0)'` 

equal to 

```js
(undefined==undefined?1:0)+(undefined==undefined?1:0)+(undefined==undefined?1:0)+(undefined==undefined?1:0)
```

then run in Chrome console, the result is 4 , not 1.

and the same as the next error example, can replace to the expression

```js
undefined==undefined?1:0+undefined==undefined?1:0+undefined==undefined?1:0+undefined==undefined?1:0
```

run result should be 1, so this is not a bug

**Comment by pavelicious-dev** [comment]
Yeah, you're right.
Seems my error was that I did not explicitly enquote the string values for the formula. With quotes it works as expected.

Thank you!
