### ISSUE TITLE
Array [ ] support

### ISSUE THREAD

**Issue by patrickmatte** [shepherdwind/simple-evaluate#13]
This library is great but unfortunately, I tried to evalute an arrya with brackets and it didn't work.

const result = evaluate({ scope: { index: 1, provider: ['yo0', 'yo1', 'yo2', 'yo3'] } }, 'scope.provider[scope.index]');

It works with scope.provider.1 but for my use case, I needed the brackets

**Comment by shepherdwind** [comment]
Sorry, I didn't see the message. Here you can implement the getValue method yourself, similar to this

```js
    evaluate(data, 'scope.provider[scope.index]', {
      getValue: (context, expr) => {
        // here expr equal scope.provider[scope.index]
        return context[expr.split('.')[0]];
      },
    }).should.equal('yo0');
```

**Comment by shepherdwind** [comment]
Default getValue use https://www.npmjs.com/package/get-value . You can use a simple getValue implement
```js
    import * as get from 'get-value';
    const getValue = (context, expr) => {
      const match = expr.match(/\[(.*?)\]/);
      if (match) {
        const innerExpr = match[1];
        const prop = getValue(context, innerExpr);
        const newExpr = expr.replace(`[${innerExpr}]`, '.' + prop);
        return getValue(context, newExpr);
      }
      return get(context, expr);
    }
```

**Comment by patrickmatte** [comment]
Thanks for the update. I ended up searching for another solution and found acorn which creates an abstract syntax tree from a string expression, then I use estree-eval to evaluate the acorn tree from a context object.
https://github.com/acornjs/acorn
https://github.com/jdanyow/estree-eval

**Comment by shepherdwind** [comment]
Okay, this was originally focused on arithmetic and logical expression calculations in JavaScript, so it does not include complete JavaScript expressions.
