### ISSUE TITLE
Add Support for Templating Strings

### ISSUE THREAD

**Issue by frastlin** [shepherdwind/simple-evaluate#5]
Hello,
I would love to see support for [templating strings.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)
This would allow basic support for [file templates](https://stackoverflow.com/questions/42881438/template-literals-from-external-file/42881547) and easier syntax for evaluating strings.

`evaluate({a:22}, "'I am ' + a + ' years old today'")`
vs
```
evaluate({a:22}, "\`I am  ${a} years old today\`")
```

If you still keep the other restrictions, that's fine, but allowing simple expressions within ${} would be extremely useful.

**Comment by shepherdwind** [comment]
Why do you need this feature. I think maybe you just need use a javascript template engine.

**Comment by frastlin** [comment]
1. This is part of ES6, so should be supported by this tool
2. I don't want to use syntax that's not JS
3. I'm already using this to evaluate a boolion in the same script, so would love to just run the same function without worrying about another dependency
4. For more complex expressions, the JS in this tool is much less verbose and more powerful than most templating engines.

**Comment by shepherdwind** [comment]
I add a pull request. You can check it, To see if it meets your needs

**Comment by frastlin** [comment]
Looks good, thank you!

**Comment by shepherdwind** [comment]
new version published, you can try it.
