### ISSUE TITLE
Export ES5 compatible dist please?

### ISSUE THREAD

**Issue by Charuru** [shepherdwind/simple-evaluate#8]
This would be helpful for some environments if possible, thanks.

**Comment by shepherdwind** [comment]
This repo build by tsc wich  `compilerOptions.target = 'es5': 

https://github.com/shepherdwind/simple-evaluate/blob/f949f1a746eb634cd97f11c8ed0ed7680e7e7970/tsconfig.json#L4

The build target should support es5 ? Is there any problem?
